### ISSUE TITLE
在format超长字符串的时候，多次把va_list ap传入vsnprintf中可能会导致不确定的行为？

### ISSUE THREAD

**Issue by xyuf** [cloudwu/cstring#4]
云风老师您好，我在仿造你的程序写自己的字符串类的时候，发现生成的字符串有错误，仔细分析原因，认为问题应该出在vsnprintf这个函数的调用处，根据manpage

> The  functions  vprintf(),  vfprintf(),  vdprintf(),  vsprintf(),  vsnprintf()  are equivalent to the functions printf(), fprintf(), dprintf(), sprintf(), snprintf(), respectively, except that they are called with a va_list instead of a  variable number of arguments.  These functions do not call the va_end macro.  Because they invoke the va_arg macro, the value of ap is undefined after the call.  See stdarg(3).

vsnprintf会修改传入的ap，所以如果程序在第一次调用vsnprintf发现buffer空间不够长之后，再次调用vsnprintf，就会出现未定义行为。

您提供的代码在我的64位linux机器上无法编译，把Makefile中的-march=i686改为-m32之后，测试没有发现问题，但是删掉-m32之后测试也会出现错误。

**Comment by cloudwu** [comment]
我疏忽了，已经修正。谢谢。

**Comment by ghost** [comment]
谢谢云风老师。
