### ISSUE TITLE
哈希表没有实现碰撞检测

### ISSUE THREAD

**Issue by linw789** [cloudwu/cstring#5]
如果把`hash_blob`函数的实现改成直接`return 1;`，然后执行下面两行代码：
```
CSTRING_LITERAL(foostr0, "bye world");
CSTRING_LITERAL(foostr1, "hello world");
```
在执行完第一行代码后`S.hash[1]`里存的是"bye world"，然而在执行完第二行代码后`S.hash[1]`变成了“hello world"。

在函数`interning`末尾的这行代码`si->hash[index] = n;`之前，`index`并没有更新。

**Comment by cloudwu** [comment]
所以，这有什么问题？

**Comment by linw789** [comment]
任何一个之前已经被"interned"的字符串有可能被另一个拥有相同哈希值的字符串覆盖。
不好意思，如果这是有意为之的话，请关闭这个问题。

**Comment by cloudwu** [comment]
你需要提供一个使用公开 API 制作的错误案例，不要针对内部函数解释。

**Comment by linw789** [comment]
对不起，是我理解错了。`interning`函数有对哈希进行碰撞检测。
